title: Data Responsibly Courses
description: This is a repo for all Data Responsibly related courses.
email: stoyanovich@nyu.edu

baseurl: ""
url: "https://DRcourses.github.io"

include:
  - _pages

sass:
  style: :compressed
  sass_dir: _sass

theme: jekyll-theme-primer