title: Data Responsibly Courses
description: This is a repo for all Data Responsibly related courses.
email: stoyanovich@nyu.edu

baseurl: "https://dataresponsibly.github.io/courses/"
url: "https://dataresponsibly.github.io/courses/"


sass:
  style: :compressed
  sass_dir: _sass

theme: jekyll-theme-primer