title: Data Responsibly Courses
description: This is a repo for all Data Responsibly related courses.
email: stoyanovich@nyu.edu

baseurl: ""
url: ""


sass:
  style: :compressed
  sass_dir: _sass

theme: jekyll-theme-primer